### ISSUE TITLE
Grid Line Breaks

### ISSUE THREAD

**Issue by joshuacole** [OwlyStuff/amazium#102]
Question about how rows work, and if this is just a bug.

It used to be I could run a loop within a row to create a grid of portfolio images like so:

```html
<section id="portfolio">
	<div class="row">
		<!-- Start Loop -->
		<div class="grid-6">
			STUFF
		</div>
		<!-- End Loop -->
		<!-- Run Loop 5 more Times (3 Rows, 2 Columns) -->
	</div>
</section>
````

When I run this same loop in Amazium 4.0 the grid shrinks down to have six images in one row, rather than wrapping or line breaking. Is that something different with the new css flex or is that me using Amazium 4.0 before it's had the kinks run out. 

I had pulled this repository open to download the script again for a new project and saw that you all had updated to 4.0, so I figured I'd try it out and now I'm being annoying guy asking too many questions.

**Comment by retober** [comment]
No you are right. I tested your issue and it seems the issue is one line in the `_grid.scss`. On line **81** you have to remove the `flex:0;`. If you use the preprocessed amazium.css you have to wait until it has been fixed and made available again.

**Comment by MikeBallan** [comment]
Hi @joshuacole Ive reviewed the code and fixed it so you now can achieve what the old version of Amazium let you do. #103

**Comment by catchamonkey** [comment]
@joshuacole if you can check that does what you're after too, i'll merge and tag a new release.
Thanks!

**Comment by MikeBallan** [comment]
Opps, closed this too soon, We will tag a new release and then you can pull down and test!

**Comment by catchamonkey** [comment]
New build published https://github.com/OwlyStuff/amazium/releases/tag/v4.0.3

**Comment by joshuacole** [comment]
Looks like it's working. Thanks!
