### ISSUE TITLE
columns-1-mobile

### ISSUE THREAD

**Issue by dyu** [OwlyStuff/amazium#111]
Your tutorial in http://www.amazium.co.uk/structure/columns says you can use that.
That css rule is not present in your https://github.com/OwlyStuff/amazium/releases/download/v4.1.2/amazium.css

**Comment by catchamonkey** [comment]
Yes that does appear to be the case, the only ones for mobile are the standard single, and columns-2-mobile.

This feels correct though, @MikeBallan is this a documentation problem, rather than missing classes?

Or is this a regression that they have been removed?

**Comment by MikeBallan** [comment]
Docs have been updated as there is no columns-1-mobile class. Thanks
