### ISSUE TITLE
inline-child--width--n tags

### ISSUE THREAD

**Issue by fthylmz** [OwlyStuff/amazium#114]
They must be named wrong, shouldn't be inline-child--grid-n? 

`    .inline-parent .inline-child--width-1,
    .inline-parent .inline-child--width-2,
    .inline-parent .inline-child--width-3,
    .inline-parent .inline-child--width-4,
    .inline-parent .inline-child--width-5,
    .inline-parent .inline-child--width-6,
    .inline-parent .inline-child--width-7,
    .inline-parent .inline-child--width-8,
    .inline-parent .inline-child--width-9 {
        width: 100%
    }`

**Comment by catchamonkey** [comment]
Will consider for next major release, but don't want any un-needed BC breaks so can't do that really.
Thanks.
