### ISSUE TITLE
Remove MavenPro

### ISSUE THREAD

**Issue by retober** [OwlyStuff/amazium#123]
I think it would be nice to remove the Maven Pro in the next release (v5). As a starting point for new projects i think it is not necessary to include a font, because mostly other fonts are needed. There are very few use cases for the included font. Could it be removed in the next release? The css files referencing it could call a system font.

What are your thoughts about it ? @catchamonkey @MikeBallan

**Comment by catchamonkey** [comment]
Works for me, i'm happy to keep it lighter and simpler, was where amazium started out right @MikeBallan ?

**Comment by MikeBallan** [comment]
Yes agreed V5 has removed all ref to the font in favour of setting the base font to be ```font-family:'sans-serif';```

**Comment by catchamonkey** [comment]
This is going in v5 which will be released as stable very shortly so closing this.

Thanks!

**Comment by diomed** [comment]
It's funny how you suddenly don't see value of specific font which distinguished amazium from other CSS frameworks.

**Comment by retober** [comment]
I think it shouldn't be the included font which distinguishes 'amazium' from other CSS frameworks. I can only speak for myself but I see 'amazium' as a foundation on which I build my sites upon. And a foundation should not include things that are guaranteed to be removed. It's a matter of seconds to include your own font.

**Comment by MikeBallan** [comment]
I agree, I built Amazium to be just that a foundation to build site on and the inclusion of fonts is  pointless unless you intend to alway use Maven Pro which is a nice font by the way :)
