### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fmunizm** [OwlyStuff/Amazium#53]
Hi.

I´m trying to use Amazium and i like it! But i don't understand how can i change or create new validations like password, text field count chars etc.

Can you help me please.

Thank you.

**Comment by p2or** [comment]
Hi fmunizm,

there is a forms.html document in the current release. Basic validation is also included. Just copy the markup what you need for your purposes.

Hope this helps.

**Comment by catchamonkey** [comment]
Hi,

Yes that's correct.
The validation in the examples is using HTML validation, via the type property of the inputs.

Things like type=email, type=url and so on.

You can also use the ```pattern``` property if you want to specify a regex that must match.

http://www.html5rocks.com/en/tutorials/forms/constraintvalidation/

**Comment by fmunizm** [comment]
Thank you for this instructions Catchamonkey. I'm reading this now and I believe that this solution is very good for my need. , 

P2or, I'm using the forms.html as sample. But, i can't create or change the validation options?i.e.  I need to verify the password lenght, if the confirmation password is equal to password, the text fields lenght... and I want to show the Amazium messages, as a red bar (tag small). Its a beautifull solution.

Thank you all!!
