### ISSUE TITLE
Rules to generic: Can´t use span or small inseide form or fieldset

### ISSUE THREAD

**Issue by DavidWiesner** [OwlyStuff/Amazium#56]
Hi,

first thanks for your great and simple theme. I use this theme very often. But there are some css rules that are to generic and break some of my stuff. 

`form.css`
```css
form span         {/*...*/}
fieldset small    {/*...*/}
/*...*/
input[type="checkbox"] + label + small
/*...*/
input[type="radio"] + label + small
/*...*/
.hide-lables fieldset.error input + small,
.hide-lables fieldset.error select + small,
.hide-lables fieldset.error textarea + small
.hide-lables small
```
Because of this to selectors I can´t really use a `span` or `small` element inside my forms. Also `form span`  change the inline element `span` into a block element. I use `span` very often for inline styling e.g.: changing a text color. I´m not sure for what you are using this selector. Disable the `display:block` and the `margin` properties doesn´t change anything in your examples, because `.radio > span` or `.checkbox > span` will take over.
Also I use small to only changing the size of the inner text. In the `hide-labels` the `small` element will also be hidden.
So you may wanna change this selectors to something like this:
`form.css`
```css
form .form-block         {/*...*/}
fieldset .error    {/*...*/}
/*...*/
input[type="checkbox"] + label + .error
/*...*/
input[type="radio"] + label + .error
/*...*/
.hide-lables fieldset.error input + .error,
.hide-lables fieldset.error select + .error,
.hide-lables fieldset.error textarea + .error
.hide-lables .error
```

It´s just an recommendation but in the current state, I always have to change this values before i can use your theme.

regards,
David

**Comment by MikeBallan** [comment]
Thank you, A very good point you raised here, I'll take a look at reworking the forms span & small to use a class rather then targeting them directly.

**Comment by shahrukhomar** [comment]
Thanks @DavidWiesner 

@MikeBallan can we see if there any more rules like such in other components and bundle all the fixes in one go?

**Comment by MikeBallan** [comment]
@shahrukhomar Sure ill take an audit of then CSS and see what else there is we can apply this too..!
