### ISSUE TITLE
Keep the fluid sperate from the pixel grid

### ISSUE THREAD

**Issue by retober** [OwlyStuff/amazium#76]
I have seen your newest commit (4.0 pre 9) and i would like to point out that it is more convenient to keep the two grids seperate from each other. This way i can include or exclude (SASS) the different versions as needed. And it is clearer and more practical to adjust certain values if the two grids aren't merged together.

By the way i'm preparing some improvements for the grid and would like to contribute, are you ok with a pull request?

_Preview of my improvements:_ http://codepen.io/retober/pen/LNweww

**Comment by catchamonkey** [comment]
Hey @retober yes that's an interesting point on keeping the SCSS files separate.
We are actively working on a flexbox implementation of the fluidgrid which will become the default and only fluid version in v4.

if you have some changes then go ahead and send a PR thanks, be easier to see what your changes are when it can be diffed! :)

**Comment by MikeBallan** [comment]
Hey, We have moved the grid to be flexbox which made the codebase smaller and less confusing between the normal fixed and fluid versions. So seperating these into two different file would be pointless as the fluid.css file would only have one class.

See #77 The amazium.co.uk site will be updated shortly for the new v4.
