### ISSUE TITLE
Broken in Safari?

### ISSUE THREAD

**Issue by joshuacole** [OwlyStuff/amazium#99]
Just installed V04 and the grid seems broken in Safari. Even your website the grid doesn't appear to be working.

**Comment by MikeBallan** [comment]
Hi, Yes we have noticed this issue and have done a PR #97 with the fix for it, We hope to merge it with the master ASAP, Thanks

**Comment by catchamonkey** [comment]
Fix merged and tagged to 4.0.1.
Thanks.
